### ISSUE TITLE
Searches the contact but cant send message

### ISSUE THREAD

**Issue by saurabhdhillon** [kyleissuper/WhatsBlaster#4]
I just executed the code piece, have set up selenium, chrome drivers and everything else.
It just searches the contact name from the list waits for a while and then displays the error "Failure: couldnt find the contact name" even when it finds the contact.
I am workin on ubuntu.

**Comment by kyleissuper** [comment]
Hi there! I wasn't able to replicate the issue on my setup. If you're still looking into it, my hunch is that either:

1. The browser is slow enough that the "until" time is not long enough (maybe try 30 seconds to see if that's the problem?)
2. For some reason, in your browser, WhatsApp web does not show the link inside of a `"span[title='{ contact_name }']"` structure? If it were me, I'd try to look for the element and see if it tallies with this CSS query.
